### ISSUE TITLE
Loading error for /random/

### ISSUE THREAD

**Issue by sunarch** [cjerrington/StaticQuest#5]
**Describe the bug**
The loading of '/random.js' fails with a 404. (Technically it gets blocked by the browser because it tries to load the HTML of the 404 page as JS.)

**To Reproduce**
1. Go to [https://static.quest/random/](https://static.quest/random/)
2. Get stuck on 'redirecting...'

**Expected behavior**
Redirection to a random member's site.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Firefox

**Comment by cjerrington** [comment]
Do you allow JavaScript?

**Comment by sunarch** [comment]
`random.js` now loads correctly, but `members.json` fails to load with a 404.

**Comment by sunarch** [comment]
Getting closer, now it redirects but appends the url: `https://static.quest/random/URL/`

**Comment by sunarch** [comment]
Yeah I just found out as well and edited the previous post, but you were faster:)

It works great now!
