### ISSUE TITLE
Link labels

### ISSUE THREAD

**Issue by sunarch** [cjerrington/StaticQuest#6]
I didn't want to PR this until I know your thoughts on it:

I was thinking when readying the page that the SSG list could include the language that they use for easier orientation.

Also, the "Just start a blog" page could include the name of the authors in the list, but this may be a more personal navigational preference.

If you agree with either of these, I'll PR them for you, if not, no worries:)

**Comment by cjerrington** [comment]
On the section [here](https://static.quest/posts/static-site-generators/#static-site-generators) I think adding the language the SSG is using could be helpful. A table might be best. Could either put this in {Eleventy Data](https://www.11ty.dev/docs/data/) or a direct table. 

I like the author idea too. 

Example: 
- [Year in review](https://claytonerrington.com/blog/year-in-review/) by [Clayton Errington](https://claytonerrington.com)

**Comment by sunarch** [comment]
For the languages: Yeah, that's the section I meant, too. Are you sure about the table? I initially thought that would be too dominant visually, but I could be wrong. I initially thought only in parens after the list items.

For the authors: The double link (link on the author too) could be omitted, since the link already leads to that site. What do you think?

**Comment by cjerrington** [comment]
Thanks for the update, merged!

**Comment by sunarch** [comment]
You're welcome!
